const APP_ACTIONS = {
  CONFIG_LOADED: 'CONFIG_LOADED'
}

const PRODUCT_LIST_ACTIONS = {
  SEND_PRODUCT_LIST_REQUEST: 'SEND_PRODUCT_LIST_REQUEST',
  FETCH_PRODUCT_LIST_SUCCESS: 'FETCH_PRODUCT_LIST_SUCCESS',
  FETCH_PRODUCT_LIST_ERROR: 'FETCH_PRODUCT_LIST_ERROR',
  CLEAR_ALL_NOTIFICATIONS: 'CLEAR_ALL_NOTIFICATIONS',
}

export default {
  ...APP_ACTIONS, ...PRODUCT_LIST_ACTIONS,
}